// layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Navbar */}
        <nav className="w-full bg-white shadow p-4">
          <ul className="flex justify-between max-w-4xl mx-auto">
            <li><Link href="/" className="text-black">Home</Link></li>
             <li><Link href="/food" className="text-black">Food Listing</Link></li>
            <li><Link href="/about" className="text-black">About</Link></li>
           
          </ul>
        </nav>

        {/* Page content */}
        <div className="p-8">{children}</div>
      </body>
    </html>
  );
}